### ISSUE TITLE
Fix: Support for RobotWare 7 in Remote Connection component

### ISSUE THREAD

**Issue by ar0551** [RobotComponents/RobotComponents#105]
Currently, the Remote Connection component returns the following error when trying to upload on a RobotWare 7 controller:
1. Solution exception:C004A00C : File not found or could not be opened for reading.
LoadModuleFile

**Comment by arjendeetman** [comment]
Fixed in [v2.0.3](https://github.com/RobotComponents/RobotComponents/releases/tag/2.0.3)

@ar0551 Can you test it on a physical controller? At least it works on a virtual controller now. 

Best,

Arjen 

[![ko-fi](https://ko-fi.com/img/githubbutton_sm.svg)](https://ko-fi.com/K3K1791RX)

**Comment by ar0551** [comment]
Not in the lab for the next two weeks, but will test it as soon as I am there.

**Comment by arjendeetman** [comment]
Fixed and released in version [2.0.4](https://github.com/RobotComponents/RobotComponents/releases/tag/2.0.4). 

Best,

Arjen 

[![ko-fi](https://ko-fi.com/img/githubbutton_sm.svg)](https://ko-fi.com/K3K1791RX)
