### ISSUE TITLE
ConfData Name Causes Error

### ISSUE THREAD

**Issue by akudless** [RobotComponents/RobotComponents#178]
I needed to modify the Configuration Data for my movements and without thinking, I gave it the name "CONFIG_1". This resulted in an error when running the generated code at the first robtarget as declarations cannot contain any variables. 

This is an example of the error when a name is entered into the ConfData component:

VAR confdata CONFIG_1 := [0,0,0,1]
VAR robtarget APP_BOT := [[-2613.82, -2108.07, 95], [0, 0.970613, 0.240647, 0], CONFIG_1, [140.68, 9E9, 9E9, 9E9, 9E9, 9E9]];

The error was:
"Description
Expression CONFIG_1 is not a constant expression. Data for this message is not saved in any robot controller event log. If acknowledged the message will be removed. 
Actions
Any expression contained within a data declaration must be a constant expression. 1. Make sure no expression contains variables or persistent references, or function calls."

Should the Name input be removed from the Configuration Data component if it causes errors in the code generation? Or should it the use of a name for confdata create a CONST instead of a VAR? That is, if VARs don't allow for other variables to be used when declaring them, do they allow constants?

**Comment by arjendeetman** [comment]
I will check this and try to reproduce the error. Probably, VAR needs to be replaced with CONST. I will try to check this the coming days and make a new release if needed...

**Comment by arjendeetman** [comment]
You can work around it by casting a text 'CONST confdata CONFIG_1 := [0,0,0,1]' to the configuration data input parameter of the robot target component. Simply type it in a panel and connect it... 

For all declarations you should be able to cast the RAPID code to its declaration parameter. You can even use LOCAL, TASK, etc. that are not supported by the components itself.

**Comment by akudless** [comment]
Thanks, I hadn’t tried casting like that yet. Good to know.

**Comment by arjendeetman** [comment]
There is an example file with all casting methods. 

For confdata you need to use CONST. I will make a new release today or tomorrow.

**Comment by arjendeetman** [comment]
This issue is solved in the new release v3.0.2.
