### ISSUE TITLE
Is it possible to build a Digital Twin of a 6-DoF ABB robot with a 2-DoF dual-axis external positioner? 

### ISSUE THREAD

**Issue by MonkeyKingChina** [RobotComponents/RobotComponents#179]
Hi，

I'm a green hand of Robot Components ABB. I would like to know if it is possible to build a Digital Twin of a 6-DoF ABB robot with a 2-DoF dual-axis external positioner?

**Comment by MonkeyKingChina** [comment]
Hi,
Thanks a lot for your responses. We are planning to arrange an ABB IRB6700_200-260_IRC5 robot and a customized dual-axis positioner. We are going to use them to machine some components of complex shapes by installing a special tool head on it. When the robot does the machining job in real world, there will be a digital twin of it which will do the same thing in a virtual environment. The virtual process is not a simple simulation of the real process. In fact, it will obtain the real-time position information of the robot and give real-time feedback controlling signal to the robot as well to achieve the optimal processing actions. However, we are green hands of robots. We are not so clear about how to realized that. The first problem is that we don’t know which tool is proper. I’m an amateur of Rhino and Grasshopper, and I found RC from Food4Rhino. RC looks quite nice and powerful. So, we would like know if it is possible to use RC to realized our goal. 
Best regards,
Yugang

**Comment by arjendeetman** [comment]
Hi, 

If you are not familiar with it, I advise to contact a local specialist that can help and guide you through the process and give you the trainings you need. Such advisor should also be able to help you selecting the appropriate software. 

I don't mind if you use our software or not. Again, contact a specialist in your area that can help you selecting both hardware and software. 

Best, 

Arjen
