### ISSUE TITLE
Adding a switch to toggle the document names check on/off

### ISSUE THREAD

**Issue by ar0551** [RobotComponents/RobotComponents#180]
Currently the variables name check in a document is always on. This makes the file quite slow when having a lot of components, and also causes issues when creating multiple toolpaths within a single file (where multiple targets with the same name would be possible, as long as they are separate in different toolpaths).
A component to switch the checker on/off globally would be handy.

**Comment by arjendeetman** [comment]
Hi @ar0551,

I added it in the new release. There is a Check Variable Names component now where you can disable the check for duplicate names. 

Best,

Arjen

[![ko-fi](https://ko-fi.com/img/githubbutton_sm.svg)](https://ko-fi.com/K3K1791RX)
